// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKkQHegEHu624XqzrrydjsC2lc2I9I0os',
    appId: '1:1009139091966:web:6e84d12bc64b2a001e98af',
    messagingSenderId: '1009139091966',
    projectId: 'app-estudio-600f1',
    authDomain: 'app-estudio-600f1.firebaseapp.com',
    storageBucket: 'app-estudio-600f1.firebasestorage.app',
    measurementId: 'G-8SRZ7GNYTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSPnl9HT43htZ45FpcThMfein7MmYkr24',
    appId: '1:1009139091966:android:09b502e6373080261e98af',
    messagingSenderId: '1009139091966',
    projectId: 'app-estudio-600f1',
    storageBucket: 'app-estudio-600f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADl4Ua_yL_8OPrpw7z34LwoLCxgVHYAMc',
    appId: '1:1009139091966:ios:43f93552c96221201e98af',
    messagingSenderId: '1009139091966',
    projectId: 'app-estudio-600f1',
    storageBucket: 'app-estudio-600f1.firebasestorage.app',
    iosBundleId: 'com.example.appEstudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADl4Ua_yL_8OPrpw7z34LwoLCxgVHYAMc',
    appId: '1:1009139091966:ios:43f93552c96221201e98af',
    messagingSenderId: '1009139091966',
    projectId: 'app-estudio-600f1',
    storageBucket: 'app-estudio-600f1.firebasestorage.app',
    iosBundleId: 'com.example.appEstudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKkQHegEHu624XqzrrydjsC2lc2I9I0os',
    appId: '1:1009139091966:web:0a17b2c8112426371e98af',
    messagingSenderId: '1009139091966',
    projectId: 'app-estudio-600f1',
    authDomain: 'app-estudio-600f1.firebaseapp.com',
    storageBucket: 'app-estudio-600f1.firebasestorage.app',
    measurementId: 'G-9RRFPSW6RY',
  );
}
